; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

monitor_speed = 115200

lib_deps = TFT_eSPI

build_flags =
  ;###############################################################
  ; TFT_eSPI library setting here (no need to edit library files):
  ;###############################################################
  -D USER_SETUP_LOADED=1                        ; Set this settings as valid
  -D ESP32_PARALLEL=1                           ; Set parallel control
  -D ILI9486_DRIVER=1                           ; Select ILI9486 driver
;   -D TFT_WIDTH=240                              ; Set TFT size
;   -D TFT_HEIGHT=320
  -D TFT_CS=1                                   ; Chip select control pin
  -D TFT_DC=3                                   ; Data Command control pin - must use a pin in the range 0-31. Also known as LCD_RS
  -D TFT_RST=22                                 ; Reset pin
  -D TFT_WR=21                                  ; Write strobe control pin - must use a pin in the range 0-31
  -D TFT_D0=25                                  ; Must use pins in the range 0-31 for the data bus
  -D TFT_D1=26                                  ; so a single register write sets/clears all bits
  -D TFT_D2=27
  -D TFT_D3=14
  -D TFT_D4=12
  -D TFT_D5=13
  -D TFT_D6=16
  -D TFT_D7=17
  -D LOAD_GFXFF=1
  ; -D LOAD_FONT2=1
  ; -D LOAD_GLCD=1
